### ISSUE TITLE
[1.19.2 forge] bug

### ISSUE THREAD

**Issue by PHAT00100** [adam9899/BetterCombat#2]
when leaving the world and entering again Without leaving the game, unable to enter the world. sorry for my bad english
It says : ![Screenshot (6)](https://user-images.githubusercontent.com/111385709/186051353-15cf764b-9da8-4a41-9e4c-5c74d07be238.png)

**Comment by PHAT00100** [comment]
[debug.log](https://github.com/LukeGrahamLandry/BetterCombat/files/9398841/debug.log)
[latest.log](https://github.com/LukeGrahamLandry/BetterCombat/files/9398842/latest.log)

**Comment by LukeGrahamLandry** [comment]
thanks
issue with trying to cache encoded packets that are sent by forge
ZsoltMolnarrr/BetterCombat ([commit](https://github.com/ZsoltMolnarrr/BetterCombat/commit/ce9a8865ded22c0936be3c6660fbf19c86d3a6eb)) has a fix and so does the dev version of ForgedFabric
