### ISSUE TITLE
BetterCombat 1.16.5 Two-handed Idle Animation Bug

### ISSUE THREAD

**Issue by Sazuzaki** [adam9899/BetterCombat#3]
Heyo, just thought I should report this here. Claymores have constant jittering to them.

https://www.youtube.com/watch?v=YMhr6wKcb_4&ab_channel=Sazuzaki

Forge: 36.2.39, also tested on 36.2.34

Mods: Tested with only BetterCombat 1.0.13.build.2 installed.

Edit: This applies to every weapon with a two-handed/unique idle stance, like Spears or Katanas.

Thanks!

**Comment by LukeGrahamLandry** [comment]
fixed in latest release

https://user-images.githubusercontent.com/40009893/199159291-34065e92-c445-4af8-94b2-4958d8bded57.mov
