### ISSUE TITLE
(1.16.5) Swapping a two-handed weapon with F deletes the weapon

### ISSUE THREAD

**Issue by RecyclingTiger** [adam9899/BetterCombat#4]
If you press F (swap with offhand keybind) the two handed weapon goes to your offhand. So far nothing wrong. **However,** if you press it again, the item gets completely deleted.

Does not occur in the 1.18 forge version.

**Comment by LukeGrahamLandry** [comment]
might be fixed in [1.4.5.2](https://github.com/LukeGrahamLandry/BetterCombat/releases/tag/1.4.5.2%2B1.16). could you link me a mod that adds a two handed weapon so I can test it without dealing with making a datapack?

**Comment by LukeGrahamLandry** [comment]
found one. fixed in latest release.

https://user-images.githubusercontent.com/40009893/199159220-b8eb4dbe-e329-41af-9a60-7240d76f8ca8.mov
