### ISSUE TITLE
[1.16.5 forge] Server crashes on startup

### ISSUE THREAD

**Issue by kevnoa3095** [adam9899/BetterCombat#5]
I installed this mod on my server, and the server crashed during startup.

Forge: 1.16.5-36.2.39
Mods: bettercombat-1.0.13+1.16-build.2
           cloth-config-4.16.91-forge
           forgedfabric-0.0.4+1.16
           player-animation-lib-forge-0.3.5+1.16.5

[latest.log](https://github.com/LukeGrahamLandry/BetterCombat/files/9810620/latest.log)

**Comment by LukeGrahamLandry** [comment]
fixed by [1.4.5.1](https://github.com/LukeGrahamLandry/BetterCombat/releases/tag/1.4.5.1%2B1.16)
